config/routes.rb
Rails.application.routes.draw do
  root :to => "web/boards#show"

  scope module: :web do
    resource :board, only: :show
    resource :session, only: [:new, :create, :destroy]
    resources :developers, only: [:new, :create]
    resources :password_resets, only: [:new, :create, :edit, :update] 
  end
  
  namespace :admin do
    resources :users
  end

  namespace :api do
    namespace :v1 do
      resources :tasks, only: [:index, :show, :create, :update, :destroy] do
        member do
          put 'attach_image'
          put 'remove_image'
        end
      end
      resources :users, only: [:index, :show]
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  mount Sidekiq::Web => '/admin/sidekiq'
  
end

app/views/layouts/application.html.slim
 doctype html
 html lang="en"
   head
     meta charset="utf-8"
     meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
     meta name="viewport" content="width=device-width, initial-scale=1.0"
     title= content_for?(:title) ? yield(:title) : "Task Manager"
     link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"
     = stylesheet_link_tag "application"
     = csrf_meta_tags
     - if !Rails.env.development?
       = stylesheet_packs_with_chunks_tag "application", media: "all"


   body
     = javascript_packs_with_chunks_tag 'application'
     header.mdl-layout__header
       .mdl-layout__header-row
         .material-icons tab
         label.mdl-button.mdl-js-button.mdl-button--icon
           i.material-icons
         span.mdl-layout-title
           = "Task Manager"
         .mdl-layout-spacer
         nav.mdl-navigation
           = link_to "Board", board_path, class: 'mdl-navigation__link'
           - if current_user
             - if current_user.is_a? Admin
               = link_to "Admin page", admin_users_url, class: 'mdl-navigation__link'
             = current_user.first_name
             = link_to "Log out", session_path, method: "delete", confirm: "confirm?", class: 'mdl-navigation__link'
           - else
             = link_to "Sign in", new_session_path, class: 'mdl-navigation__link'
             = link_to "Sign up", new_developer_path, class: 'mdl-navigation__link'

     main#main.mdl-layout__content
       .page-content
         - flash.each do |message_type, message|
            div.alert
              = message
         = yield
     footer#footer.mdl-mini-footer
       .mdl-mini-footer__left-section
         .mdl-logo
           | &copy; Dualboot Learn 2021

app/views/layouts/user_mailer.html.slim
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" >
    <title></title>
  </head>
  <body bgcolor="#efefef" style="padding: 0; margin: 0;">
    <table border="0" cellpadding="0" cellspacing="0" width="100%">
      <tr>
        <td align="center">
          <table width="600" border="0" cellpadding="0" cellspacing="0">
            <tr>
              <td bgcolor="#3F52B5" align="center" style="padding: 30px 0;">
                <span style="color:#ffffff; font-size: 20px; font-family:Arial, Helvetica, sans-serif;"><b>Task Board Project</b></span>
              </td>
            <tr>
              <td>
                <table border="0" cellpadding="30px" cellspacing="0" width="100%">
                  <tr>
                    <td>
                       = yield
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
            <tr>
              <td align="center" bgcolor="#C0C0C0">
                | &copy; Dualboot Learn #{Date.today.year}
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>